# Osaka Jade
nvim_plugin       = "ribru17/bamboo.nvim"
nvim_colorscheme  = "bamboo"
appearance        = "dark"

# Core palette
accent            = "#509475"
background        = "#111c18"
background_alt    = "#23372B"
background_subtle = "#32473B"
foreground        = "#C1C497"
foreground_dim    = "#81B8A8"
inactive          = "#53685B"
urgent            = "#FF5345"
success           = "#549e6a"
warning           = "#459451"
cursor            = "#F7E8B2"

# Terminal 16-color palette (for kitty)
color0  = "#111c18"
color1  = "#FF5345"
color2  = "#549e6a"
color3  = "#459451"
color4  = "#509475"
color5  = "#D2689C"
color6  = "#2DD5B7"
color7  = "#C1C497"
color8  = "#53685B"
color9  = "#db9f9c"
color10 = "#63b07a"
color11 = "#E5C736"
color12 = "#ACD4CF"
color13 = "#75bbb3"
color14 = "#8CD3CB"
color15 = "#F7E8B2"
