#!/bin/zsh
#
# This lets you quickly jump into a project directory.
#
# Type:
#
#   c <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_c`. Typically I'm using it like:
#
#    c holm<tab>/bo<tab>
#
# ...to quickly jump into holman/boom, for example.

if [ -d "$PROJECTS/$1" ]; then
    cd "$PROJECTS/$1"
fi

if [ -d "$GOPATH/src/github.com/$1" ]; then
    cd "$GOPATH/src/github.com/$1"
fi

if [ -z $1 ]; then
    cd "$PROJECTS"
fi