# ── Environment Variables ────────────────────────────────────────────────────
# vim: ft=swayconfig

set $mod      Mod4
set $term     kitty --directory $HOME
set $browser  flatpak run org.chromium.Chromium
set $launcher rofi -show drun -show-icons -theme ~/.config/rofi/drun.rasi -p ""
set $menu     rofi -show run

set $opacity     0.97
set $gaps_inner  5
set $gaps_outer  8
set $scale       1.5

# Workspace names
set $ws1  "1"
set $ws2  "2"
set $ws3  "3"
set $ws4  "4"
set $ws5  "5"
set $ws6  "6"
set $ws7  "7"
set $ws8  "8"
set $ws9  "9"
set $ws10 "10"
