# ── Clipboard ────────────────────────────────────────────────────────────────
# vim: ft=swayconfig

# Paste current clipboard into focused window
bindsym $mod+v exec wl-paste -n | wtype -

# Clipboard history picker (rofi + cliphist)
bindsym $mod+shift+v exec cliphist list | rofi -dmenu -p "clipboard" -theme ~/.config/rofi/cliphist.rasi | cliphist decode | wl-copy
