# Generated by theme-set — do not edit directly

[global]
    ### Display ###
    monitor = 0
    follow = keyboard

    ### Geometry ###
    width = (0, 380)
    height = (0, 200)
    origin = top-right
    offset = (16, 48)
    scale = 0
    notification_limit = 5

    ### Progress bar ###
    progress_bar = true
    progress_bar_height = 6
    progress_bar_frame_width = 1
    progress_bar_min_width = 150
    progress_bar_max_width = 340
    progress_bar_corner_radius = 3
    progress_bar_corners = all
    icon_corner_radius = 4
    icon_corners = all
    indicate_hidden = yes

    ### Appearance ###
    transparency = 5
    separator_height = 1
    padding = 10
    horizontal_padding = 12
    text_icon_padding = 8
    frame_width = 2
    frame_color = "{{ accent }}"
    gap_size = 6
    separator_color = frame
    sort = yes
    corner_radius = 6
    corners = all

    ### Text ###
    font = Cascadia Code NF 11
    line_height = 2
    markup = full
    format = "<b>%s</b>\n%b"
    alignment = left
    vertical_alignment = center
    show_age_threshold = 60
    ellipsize = middle
    ignore_newline = no
    stack_duplicates = true
    hide_duplicate_count = false
    show_indicators = yes

    ### Icons ###
    enable_recursive_icon_lookup = true
    icon_theme = Adwaita
    icon_position = left
    min_icon_size = 24
    max_icon_size = 48

    ### History ###
    sticky_history = yes
    history_length = 20

    ### Misc ###
    dmenu = /usr/bin/rofi -dmenu -p dunst
    browser = /usr/bin/xdg-open
    always_run_script = true
    title = Dunst
    class = Dunst
    ignore_dbusclose = false
    force_xwayland = false
    force_xinerama = false
    mouse_left_click = close_current
    mouse_middle_click = do_action, close_current
    mouse_right_click = close_all

[experimental]
    per_monitor_dpi = false

# ── Urgency levels ──────────────────────────────────────────────────────────

[urgency_low]
    background = "{{ background }}"
    foreground = "{{ foreground_dim }}"
    frame_color = "{{ inactive }}"
    timeout = 4
    default_icon = dialog-information

[urgency_normal]
    background = "{{ background }}"
    foreground = "{{ foreground }}"
    frame_color = "{{ accent }}"
    timeout = 6
    default_icon = dialog-information

[urgency_critical]
    background = "{{ background }}"
    foreground = "{{ urgent }}"
    frame_color = "{{ urgent }}"
    timeout = 0
    default_icon = dialog-error

# ── Per-app rules ───────────────────────────────────────────────────────────

# Screenshot notifications — green accent
[screenshots]
    summary = "Screenshot*"
    frame_color = "{{ success }}"
    foreground  = "{{ success }}"
    timeout = 3

# Volume / brightness — short timeout, low urgency style
[volume_brightness]
    summary = "Volume*"
    timeout = 2

[brightness]
    summary = "Brightness*"
    timeout = 2

# Nightlight
[nightlight]
    summary = "Nightlight*"
    frame_color = "{{ warning }}"
    foreground  = "{{ warning }}"
    timeout = 3
