/* Generated by theme-set */
* {
    bg:         {{ background }};
    bg-alt:     {{ background_alt }};
    fg:         {{ foreground }};
    fg-dim:     {{ foreground_dim }};
    accent:     {{ accent }};
    accent-dim: {{ background_alt }};
    inactive:   {{ inactive }};
    urgent:     {{ urgent }};
    border:     2px;
    spacing:    0;
}
