[tools]
"aqua:joshmedeski/sesh" = "latest"
azure = { version = "latest", uvx_args = "--prerelease=allow" }
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
helm = "latest"
kubectl = "latest"
lua = "latest"
starship = "latest"
terraform = "latest"
terramate = "latest"
zoxide = "latest"
