# Catppuccin Latte (light)
nvim_plugin      = "catppuccin/nvim"
nvim_plugin_name = "catppuccin"
nvim_colorscheme = "catppuccin-latte"
accent             = "#1e66f5"
background         = "#eff1f5"
background_alt     = "#e6e9ef"
background_subtle  = "#dce0e8"
foreground         = "#4c4f69"
foreground_dim     = "#8c8fa1"
inactive           = "#bcc0cc"
urgent             = "#d20f39"
success            = "#40a02b"
warning            = "#df8e1d"
cursor             = "#dc8a78"

color0  = "#bcc0cc"
color1  = "#d20f39"
color2  = "#40a02b"
color3  = "#df8e1d"
color4  = "#1e66f5"
color5  = "#ea76cb"
color6  = "#179299"
color7  = "#5c5f77"
color8  = "#acb0be"
color9  = "#d20f39"
color10 = "#40a02b"
color11 = "#df8e1d"
color12 = "#1e66f5"
color13 = "#ea76cb"
color14 = "#179299"
color15 = "#6c6f85"
