# Ristretto
nvim_plugin       = "gthelding/monokai-pro.nvim"
nvim_colorscheme  = "monokai-pro"
appearance        = "dark"

# Core palette
accent            = "#f38d70"
background        = "#2c2525"
background_alt    = "#3d2f2a"
background_subtle = "#403e41"
foreground        = "#e6d9db"
foreground_dim    = "#72696a"
inactive          = "#72696a"
urgent            = "#fd6883"
success           = "#adda78"
warning           = "#f9cc6c"
cursor            = "#e6d9db"

# Terminal 16-color palette (for kitty)
color0  = "#2c2525"
color1  = "#fd6883"
color2  = "#adda78"
color3  = "#f9cc6c"
color4  = "#f38d70"
color5  = "#a8a9eb"
color6  = "#85dacc"
color7  = "#e6d9db"
color8  = "#72696a"
color9  = "#ff8297"
color10 = "#c8e292"
color11 = "#fcd675"
color12 = "#f8a788"
color13 = "#bebffd"
color14 = "#9bf1e1"
color15 = "#e6d9db"
