# Solitude
nvim_plugin       = "ficcdaf/ashen.nvim"
nvim_colorscheme  = "ashen"
appearance        = "dark"

# Core palette
accent            = "#798186"
background        = "#101315"
background_alt    = "#101315"
background_subtle = "#343d41"
foreground        = "#cacccc"
foreground_dim    = "#4b4e55"
inactive          = "#4b4e55"
urgent            = "#565d60"
success           = "#9fa5a9"
warning           = "#d9dbdc"
cursor            = "#a5aeb4"

# Terminal 16-color palette (for kitty)
color0  = "#101315"
color1  = "#565d60"
color2  = "#9fa5a9"
color3  = "#d9dbdc"
color4  = "#798186"
color5  = "#aeaeae"
color6  = "#707070"
color7  = "#cacccc"
color8  = "#4b4e55"
color9  = "#de6145"
color10 = "#343d41"
color11 = "#c9c2b4"
color12 = "#5d6367"
color13 = "#9a9a9a"
color14 = "#707070"
color15 = "#a5aeb4"
