[[session]]
name = "dotfiles"
path = "~/.dotfiles"

[[session]]
name = "neovim config"
path = "~/.config/nvim"

[[session]]
name = "sesh config"
path = "~/.config/sesh"

[[session]]
name = "kitty config"
path = "~/.config/kitty"

[[session]]
name = "code"
path = "/Volumes/code"
