# Matte Black
nvim_plugin      = "tahayvr/matteblack.nvim"
nvim_colorscheme = "matteblack"
accent             = "#e68e0d"
background         = "#121212"
background_alt     = "#1a1a1a"
background_subtle  = "#222222"
foreground         = "#bebebe"
foreground_dim     = "#8a8a8d"
inactive           = "#333333"
urgent             = "#D35F5F"
success            = "#FFC107"
warning            = "#f59e0b"
cursor             = "#eaeaea"

color0  = "#333333"
color1  = "#D35F5F"
color2  = "#FFC107"
color3  = "#b91c1c"
color4  = "#e68e0d"
color5  = "#D35F5F"
color6  = "#bebebe"
color7  = "#bebebe"
color8  = "#8a8a8d"
color9  = "#B91C1C"
color10 = "#FFC107"
color11 = "#b90a0a"
color12 = "#f59e0b"
color13 = "#B91C1C"
color14 = "#eaeaea"
color15 = "#ffffff"
