# Hackerman
nvim_plugin      = "bjarneo/hackerman.nvim"
nvim_colorscheme = "hackerman"
accent             = "#82FB9C"
background         = "#0B0C16"
background_alt     = "#12131f"
background_subtle  = "#1a1b2e"
foreground         = "#ddf7ff"
foreground_dim     = "#8a9ab0"
inactive           = "#3a3d55"
urgent             = "#ff4455"
success            = "#4fe88f"
warning            = "#50f7d4"
cursor             = "#ddf7ff"

color0  = "#0B0C16"
color1  = "#50f872"
color2  = "#4fe88f"
color3  = "#50f7d4"
color4  = "#829dd4"
color5  = "#86a7df"
color6  = "#7cf8f7"
color7  = "#85E1FB"
color8  = "#6a6e95"
color9  = "#85ff9d"
color10 = "#9cf7c2"
color11 = "#a4ffec"
color12 = "#c4d2ed"
color13 = "#cddbf4"
color14 = "#d1fffe"
color15 = "#ddf7ff"
