# Vantablack
nvim_plugin      = "bjarneo/vantablack.nvim"
nvim_colorscheme = "vantablack"
appearance = "dark"
accent             = "#8d8d8d"
background         = "#0d0d0d"
background_alt     = "#141414"
background_subtle  = "#1c1c1c"
foreground         = "#ffffff"
foreground_dim     = "#a0a0a0"
inactive           = "#3d3d3d"
urgent             = "#a4a4a4"
success            = "#b6b6b6"
warning            = "#cecece"
cursor             = "#ffffff"

color0  = "#0d0d0d"
color1  = "#a4a4a4"
color2  = "#b6b6b6"
color3  = "#cecece"
color4  = "#8d8d8d"
color5  = "#9b9b9b"
color6  = "#b0b0b0"
color7  = "#ececec"
color8  = "#fdfdfd"
color9  = "#a4a4a4"
color10 = "#b6b6b6"
color11 = "#cecece"
color12 = "#8d8d8d"
color13 = "#9b9b9b"
color14 = "#b0b0b0"
color15 = "#ffffff"
